export const ANIMALS = [
  {
    id: 'lion',
    name: 'Lions',
    emoji: '🦁',
    fact: 'The lions pace the deck with courage, recalling the boldness of Judah’s tribe.',
  },
  {
    id: 'dove',
    name: 'Doves',
    emoji: '🕊️',
    fact: 'Gentle doves wait to scout the skies just as they did in Genesis 8:8-12.',
  },
  {
    id: 'zebra',
    name: 'Zebras',
    emoji: '🦓',
    fact: 'Striped travelers who remind us that God delights in variety.',
  },
  {
    id: 'elephant',
    name: 'Elephants',
    emoji: '🐘',
    fact: 'These giants sway patiently, trusting the ark’s sturdy frame.',
  },
  {
    id: 'giraffe',
    name: 'Giraffes',
    emoji: '🦒',
    fact: 'Giraffes keep lookout above the clouds thanks to their watchtower necks.',
  },
  {
    id: 'panda',
    name: 'Pandas',
    emoji: '🐼',
    fact: 'Pandas share bamboo snacks, reminding Noah’s family to rest and rejoice.',
  },
  {
    id: 'frog',
    name: 'Tree Frogs',
    emoji: '🐸',
    fact: 'Tiny frogs cling to the ark’s beams, singing rhythm under the rainfall.',
  },
  {
    id: 'camel',
    name: 'Camels',
    emoji: '🐫',
    fact: 'Desert wanderers who carry stories of distant dunes into the ark.',
  },
  {
    id: 'owl',
    name: 'Owls',
    emoji: '🦉',
    fact: 'Night watch owls keep gentle guard while the crew sleeps.',
  },
  {
    id: 'fox',
    name: 'Foxes',
    emoji: '🦊',
    fact: 'Clever foxes tuck their tails and learn patience during the voyage.',
  },
  {
    id: 'bear',
    name: 'Bears',
    emoji: '🐻',
    fact: 'Bears hum low psalms, reminding everyone to endure with strength.',
  },
  {
    id: 'penguin',
    name: 'Penguins',
    emoji: '🐧',
    fact: 'Polar guests who waddle in faithful formation down the gangplank.',
  },
  {
    id: 'monkey',
    name: 'Monkeys',
    emoji: '🐒',
    fact: 'Monkeys swing from rafters, keeping spirits lifted on cloudy days.',
  },
  {
    id: 'koala',
    name: 'Koalas',
    emoji: '🐨',
    fact: 'Koalas nap in the highest alcoves, trusting the ark’s steady sway.',
  },
  {
    id: 'horse',
    name: 'Horses',
    emoji: '🐴',
    fact: 'Horses stamp gentle rhythms, eager for new pasture when the flood subsides.',
  },
  {
    id: 'sheep',
    name: 'Sheep',
    emoji: '🐑',
    fact: 'Faithful sheep huddle quietly, echoing the call to follow the Shepherd.',
  },
  {
    id: 'goat',
    name: 'Mountain Goats',
    emoji: '🐐',
    fact: 'Sure-footed goats dream of future peaks glistening after the storm.',
  },
  {
    id: 'turtle',
    name: 'Sea Turtles',
    emoji: '🐢',
    fact: 'Sea turtles glide through rainwater pools, charting patient paths.',
  },
  {
    id: 'rabbit',
    name: 'Hares',
    emoji: '🐇',
    fact: 'Quick-footed hares practice stillness and wait for dry ground.',
  },
  {
    id: 'raven',
    name: 'Ravens',
    emoji: '🐦‍⬛',
    fact: 'Ravens remember their first scouting flight from the ark’s open window.',
  },
];
